import { Injectable } from '@angular/core';
import { Menu } from './menu';
import { HttpClient } from '@angular/common/http';
import { Observable } from "rxjs";

@Injectable({
    providedIn: 'root'
})

export class DataService {

    baseUrl = 'https://crudcrud.com/api/b68d8de8ee1241fcb62ae03c472a989a'; // berbeda untuk setiap mahasiswa

    constructor(private http: HttpClient) {}
  
    getMenus(){
      return this.http.get(`${this.baseUrl}/menu`);
    }
  
    getMenu(id: string):Observable<any> {
      return this.http.get(`${this.baseUrl}/menu/${id}`);
    }
  
    postMenu(menu: Menu): Observable<any>  {
      delete menu._id; // we delete the id because it'll generated by server
      return this.http.post(`${this.baseUrl}/menu`, menu);
    }
  
    updateMenu(id: string, param: Menu): Observable<any> {
      return this.http.put(`${this.baseUrl}/menu/${id}`, param);
    }
  
    deleteMenu(menu: Menu): Observable<any>  {
      const id = menu._id; // we copy the original id
      return this.http.delete(`${this.baseUrl}/menu/${id}`);
    }


}
